<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
		<PackageReference Include="Hangfire.Dashboard.Basic.Authentication" Version="8.0.0" />
		<PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Swashbuckle.AspNetCore.ReDoc" Version="9.0.6" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Core\Project.DigitalMarket.Domain.Share\Project.DigitalMarket.Domain.Share.csproj" />
	  <ProjectReference Include="..\Project.DigitalMarket.Libs\Project.DigitalMarket.Libs.csproj" />
	</ItemGroup>

</Project>
