<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Project.DigitalMarket.Application.Contract\Project.DigitalMarket.Application.Contract.csproj" />
    <ProjectReference Include="..\..\..\Core\Project.DigitalMarket.Application\Project.DigitalMarket.Application.csproj" />
    <ProjectReference Include="..\..\..\Lib\Project.DigitalMarket.Host.Base\Project.DigitalMarket.Host.Base.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Project.DigitalMarket.Infrastructure.MsSql\Project.DigitalMarket.Infrastructure.MsSql.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Project.DigitalMarket.Infrastructure.Mail\Project.DigitalMarket.Infrastructure.Mail.csproj" />
  </ItemGroup>

</Project>
