<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Project.DigitalMarket.Domain\Project.DigitalMarket.Domain.csproj" />
    <ProjectReference Include="..\..\Lib\Project.DigitalMarket.Libs\Project.DigitalMarket.Libs.csproj" />
  </ItemGroup>

</Project>
